Update ubuntu/debian to include install of llvm
Added llvm to APT install line - llvm6.0 is installed on ubuntu bionic with clang, for example - but it fails to make symlinks for llvm-config for example in /usr/bin - these links remain as llvm-config-6.0 which isn't recognized by build system, and cargo build fails - setting environment variables needed to be done for each llvm binary afaik (or a bunch of them) - installing llvm installs symlinks to v6.0 binaries (or respective binaries on each platform version).  Was thinking of what happens to new users trying to build when they run into an issue with crate 700+ out of 900 something repeatedly - the build error is not clear, is not resolvable as a google search easily, and isn't readily apparent without a working knowledge of what llvm is trying to do. 

Tested on every LTS of Ubuntu (xenial, bionic, focal) and debian (jessie, stretch, buster) for the symlink behavior, not full substrate compilation. 

The error is as follows:
```
The following warnings were emitted during compilation:

warning: In file included from rocksdb/db/version_set.h:42:0,
warning:                  from rocksdb/db/compaction/compaction.h:11,
warning:                  from rocksdb/db/compaction/compaction_iterator.h:13,
warning:                  from rocksdb/db/compaction/compaction_job.h:21,
warning:                  from rocksdb/db/compaction/compaction_job.cc:22:
warning: rocksdb/db/version_builder.h:61:76: internal compiler error: Segmentation fault
warning:    VersionBuilder* version_builder() const { return version_builder_.get(); }
warning:                                                                             ^
warning: Please submit a full bug report,
warning: with preprocessed source if appropriate.
warning: See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.

error: failed to run custom build command for `librocksdb-sys v6.11.4`
```


This is an example of directory structure:

```
root@5cdc177c8650:/# ls -l /usr/bin/llvm*
lrwxrwxrwx 1 root root 38 Mar 20  2020 /usr/bin/llvm-PerfectShuffle -> ../lib/llvm-10/bin/llvm-PerfectShuffle
lrwxrwxrwx 1 root root 38 Apr 20  2020 /usr/bin/llvm-PerfectShuffle-10 -> ../lib/llvm-10/bin/llvm-PerfectShuffle
lrwxrwxrwx 1 root root 33 Apr 20  2020 /usr/bin/llvm-addr2line-10 -> ../lib/llvm-10/bin/llvm-addr2line
lrwxrwxrwx 1 root root 26 Mar 20  2020 /usr/bin/llvm-ar -> ../lib/llvm-10/bin/llvm-ar
lrwxrwxrwx 1 root root 26 Apr 20  2020 /usr/bin/llvm-ar-10 -> ../lib/llvm-10/bin/llvm-ar
lrwxrwxrwx 1 root root 26 Mar 20  2020 /usr/bin/llvm-as -> ../lib/llvm-10/bin/llvm-as
lrwxrwxrwx 1 root root 26 Apr 20  2020 /usr/bin/llvm-as-10 -> ../lib/llvm-10/bin/llvm-as
lrwxrwxrwx 1 root root 34 Mar 20  2020 /usr/bin/llvm-bcanalyzer -> ../lib/llvm-10/bin/llvm-bcanalyzer
lrwxrwxrwx 1 root root 34 Apr 20  2020 /usr/bin/llvm-bcanalyzer-10 -> ../lib/llvm-10/bin/llvm-bcanalyzer
lrwxrwxrwx 1 root root 30 Mar 20  2020 /usr/bin/llvm-c-test -> ../lib/llvm-10/bin/llvm-c-test
lrwxrwxrwx 1 root root 30 Apr 20  2020 /usr/bin/llvm-c-test-10 -> ../lib/llvm-10/bin/llvm-c-test
```

From ubuntu-focal. Without the llvm metapackage, the links for c-test would only be llvm-c-test-10, not llvm-c-test. This is from ubuntu-focal for reference, before install of llvm:

root@5cdc177c8650:/# ls -l /usr/bin/llvm*
lrwxrwxrwx 1 root root 38 Apr 20  2020 /usr/bin/llvm-PerfectShuffle-10 -> ../lib/llvm-10/bin/llvm-PerfectShuffle
lrwxrwxrwx 1 root root 33 Apr 20  2020 /usr/bin/llvm-addr2line-10 -> ../lib/llvm-10/bin/llvm-addr2line
lrwxrwxrwx 1 root root 26 Apr 20  2020 /usr/bin/llvm-ar-10 -> ../lib/llvm-10/bin/llvm-ar
lrwxrwxrwx 1 root root 26 Apr 20  2020 /usr/bin/llvm-as-10 -> ../lib/llvm-10/bin/llvm-as
lrwxrwxrwx 1 root root 34 Apr 20  2020 /usr/bin/llvm-bcanalyzer-10 -> ../lib/llvm-10/bin/llvm-bcanalyzer
lrwxrwxrwx 1 root root 30 Apr 20  2020 /usr/bin/llvm-c-test-10 -> ../lib/llvm-10/bin/llvm-c-test